name: Tensorcomputing
favicon: null
layout_spectrum: 0.5534599316306412
typography_spectrum: 0.9206744183320552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8243497342336923
  lightness: 0.1182835609652102
  saturation: 0.6506539448164403
  rhythmicContrast: 0.2524844575673342
purpose: []
